@echo off
del /Q /S "scripts\Grinder\Settings.json"
del /Q /S "scripts\Grinder\Profiles\*.mesh"
del /Q /S "scripts\Grinder\Profiles\*.json"
del /Q /S "scripts\Grinder\Profiles\*.nav"
del /Q /S "scripts\Fisher\Settings.json"
del /Q /S "scripts\Fisher\Profiles\*.mesh"
del /Q /S "scripts\Fisher\Profiles\*.json"
del /Q /S "scripts\Fisher\Profiles\*.nav"
del /Q /S "scripts\Consumables\Settings.json"
del /Q /S "scripts\PetFeeder\Settings.json"